@endpoint=http://localhost:{{$dotenv PORT}}

###
GET {{endpoint}}/api/admin/roles

###
GET {{endpoint}}/api/admin/role/1

###
POST {{endpoint}}/api/admin/role/1/link
Content-Type: application/json

{
    "roleId": 1
}

###
DELETE {{endpoint}}/api/admin/role/1/unLink
Content-Type: application/json

{
    "roleId": 3
}

###
GET {{endpoint}}/api/admin/1/roles

###
GET {{endpoint}}/api/admin/elected

###
GET {{endpoint}}/api/admin/elected/2