@endpoint=http://localhost:{{$dotenv PORT}}

###
POST {{endpoint}}/api/poll/newPoll
Content-Type: application/json

{
    "question": "Quel est votre syndicat préféré ?",
    "options":  ["CGT", "SUD", "CFDT"]
}


###
POST {{endpoint}}/api/poll/vote/6/1
Content-Type: application/json

{
    "optionId": 19
}

###
GET {{endpoint}}/api/poll/polls

###
GET {{endpoint}}/api/poll/latest

###
GET {{endpoint}}/api/poll/5/vote-status/1

###
GET {{endpoint}}/api/poll/5/options

###
DELETE {{endpoint}}/api/poll/delete/8

