@endpoint=http://localhost:{{$dotenv PORT}}

###
POST {{ endpoint }}/api/users/signup
content-type: application/json

{
    "pseudo": "Mike",
    "firstname": "Mickael",
    "lastname": "Carlucci",
    "mail": "frewmike59@yahoo.fr",
    "password": "Statue59",
    "firstQuestion": "Comment je m'appelle ?",
    "firstAnswer": "Mike",
    "secondQuestion": "J'habite dans quelle ville ?",
    "secondAnswer": "Erre",
    "centerId": 1
}

###
DELETE {{ endpoint }}/api/users/1/delete
content-type: application/json

{
    "mail": "frewmike59@yahoo.fr"
}

###
POST {{ endpoint }}/api/users/signin
content-type: application/json

{
    "mail": "frewmike59@yahoo.fr",
    "password": "Statue59"
}

###
POST {{ endpoint }}/api/users/1/mail