@endpoint=http://localhost:{{$dotenv PORT}}

###
GET {{endpoint}}/api/admin/activities

###
GET {{endpoint}}/api/admin/activity/1

###
GET {{endpoint}}/api/admin/activity/1/centers

###
POST {{endpoint}}/api/admin/addActivity
Content-Type: application/json

{
    "name": "Test 6",
    "centerId": 1
}

###
DELETE {{endpoint}}/api/admin/56/deleteActivity

###
POST {{endpoint}}/api/admin/47/updateActivity
Content-Type: application/json

{
    "name": "Non présent dans la liste"
}

###
POST {{endpoint}}/api/admin/link
Content-Type: application/json

{
    "centerId": 1,
    "activityId": 2
}