-- Revert CGT-back:V2 from pg

BEGIN;

ALTER TABLE "user" ALTER COLUMN "password" TYPE VARCHAR(50) NOT NULL;
ALTER TABLE "user" ALTER COLUMN "first_answer" TYPE VARCHAR(50) NOT NULL;
ALTER TABLE "user" ALTER COLUMN "second_answer" TYPE VARCHAR(50) NOT NULL;

COMMIT;
